#!/usr/bin/env python3
"""Generate src/palette_tables.h for the ST port's automatic palette.

Two tables:

  kSTLab        CIELAB for each of the STE's 4096 colours (L*2, a+128,
                b+128), so the quantiser can measure colour differences
                the way the eye does without floating point.
  kSTColourUse  for each level, palette number and index, the average
                share of the room pixels drawn in that colour, in tenths
                of a percent. The quantiser weighs colours by it, so a
                colour covering a quarter of the screen is not traded
                away for one that covers a few pixels.

The colour use comes from every room of every level rendered by the SDL
build with its room dump turned on (the `if (0)` block in
Game::loadLevelData, enabled by RS_DUMP=<level> in a patched copy - see
the notes in the ST port's history), in DUMP/level<L>_part<P>_room<NN>.bmp,
and from the rooms' palette numbers in the level files.

    tools/gen-palette-tables.py DUMP_DIR DATA_DIR > src/palette_tables.h
"""
import glob, os, struct, sys
from collections import Counter
from PIL import Image

dump_dir, data_dir = sys.argv[1], sys.argv[2]

def unpack(src, srcSize):
    # bytekiller, as src/unpack.cpp
    be32 = lambda o: struct.unpack('>I', src[o:o+4])[0]
    i = srcSize - 4
    size = be32(i); i -= 4
    out = bytearray(size); o = size
    crc = be32(i); i -= 4
    st = {'bits': be32(i), 'i': i - 4}
    crc ^= st['bits']
    def bit():
        b = st['bits'] & 1
        st['bits'] >>= 1
        if st['bits'] == 0:
            nb = be32(st['i']); st['i'] -= 4
            b = nb & 1
            st['bits'] = (nb >> 1) | 0x80000000
        return b
    def get(n):
        v = 0
        for _ in range(n): v = (v << 1) | bit()
        return v
    while size > 0:
        if not bit():
            if not bit(): l = get(3) + 1; off = 0
            else: l = 2; off = get(8)
        else:
            c = get(2)
            if c == 3: l = get(8) + 9; off = 0
            elif c == 2: l = get(8) + 1; off = get(12)
            else: l = c + 3; off = get(c + 9)
        size -= l
        if size < 0: l += size; size = 0
        if off:
            for _ in range(l): o -= 1; out[o] = out[o + off]
        else:
            for _ in range(l): o -= 1; out[o] = get(8)
    return bytes(out)

def room_palettes(lev_path, room):
    lev = open(lev_path, 'rb').read()
    off = struct.unpack('>I', lev[room * 4:room * 4 + 4])[0]
    tmp = unpack(lev, off)
    return [struct.unpack('>H', tmp[2 + 2 * k:4 + 2 * k])[0] for k in range(4)]

# level index -> level file per part (Game::loadLevelData)
LEVELS = {0: {0: 'LEVEL1.LEV'}, 1: {1: 'LEVEL2_1.LEV', 2: 'LEVEL2_2.LEV'}, 2: {0: 'DT.LEV'},
          3: {0: 'LEVEL3_1.LEV'}, 4: {0: 'LEVEL3_1.LEV'}, 5: {0: 'LEVEL4_1.LEV'}, 6: {0: 'LEVEL4_2.LEV'}}
NPAL = 6

use = [[[0.0] * 16 for _ in range(NPAL)] for _ in range(7)]
for L, parts in LEVELS.items():
    rooms = 0
    acc = [[0.0] * 16 for _ in range(NPAL)]
    for part, lev in parts.items():
        for f in sorted(glob.glob(os.path.join(dump_dir, 'level%d_part%d_room*.bmp' % (L, part)))):
            room = int(f.rsplit('room', 1)[1][:2])
            p1, p2, p3, p4 = room_palettes(os.path.join(data_dir, lev), room)
            # Video::AMIGA_setLevelPalettes
            slot = {0: p1, 1: p3 if L == 0 else p2, 2: p3, 3: p3, 4: p3, 8: p1, 9: p1 if L == 0 else p3, 10: p3}
            im = Image.open(f)
            hist = Counter(im.getdata())
            total = sum(hist.values())
            for e, n in hist.items():
                s, k = e >> 4, e & 15
                if s in slot and slot[s] < NPAL:
                    acc[slot[s]][k] += 100.0 * n / total
            rooms += 1
    for pn in range(NPAL):
        for k in range(16):
            use[L][pn][k] = acc[pn][k] / max(rooms, 1)

def lab(r, g, b):
    def lin(c):
        c = c * 17 / 255
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = lin(r), lin(g), lin(b)
    X = (0.4124 * r + 0.3576 * g + 0.1805 * b) / 0.95047
    Y = 0.2126 * r + 0.7152 * g + 0.0722 * b
    Z = (0.0193 * r + 0.1192 * g + 0.9505 * b) / 1.08883
    f = lambda t: t ** (1 / 3) if t > 0.008856 else 7.787 * t + 16 / 116
    return 116 * f(Y) - 16, 500 * (f(X) - f(Y)), 200 * (f(Y) - f(Z))

out = []
out.append('/* Generated by tools/gen-palette-tables.py - do not edit. */')
out.append('')
out.append('#ifndef PALETTE_TABLES_H__')
out.append('#define PALETTE_TABLES_H__')
out.append('')
out.append('// CIELAB of each STE colour 0xRGB: L*2, a+128, b+128')
out.append('static const uint8_t kSTLab[4096][3] = {')
row = []
for c in range(4096):
    L, A, B = lab((c >> 8) & 15, (c >> 4) & 15, c & 15)
    row.append('{%d,%d,%d}' % (max(0, min(255, round(L * 2))), max(0, min(255, round(A) + 128)), max(0, min(255, round(B) + 128))))
    if len(row) == 8:
        out.append('\t' + ','.join(row) + ',')
        row = []
out.append('};')
out.append('')
out.append('// share of each level\'s room pixels in each palette colour, 0.1% units')
out.append('static const uint16_t kSTColourUse[7][%d][16] = {' % NPAL)
for L in range(7):
    out.append('\t{')
    for pn in range(NPAL):
        out.append('\t\t{' + ','.join('%d' % round(v * 10) for v in use[L][pn]) + '},')
    out.append('\t},')
out.append('};')
out.append('')
# Game::_monsterListLevels: (sprite, monster) pairs; on the Amiga a monster
# is drawn with half of the object palette, entries (monster & 1) * 8 on
monsters = [[0, 0], [0, 0, 0, 1, 1, 2], [2], [1, 2], [2, 2, 3], [3, 3], [3, 3, 3]]
out.append('// per level, the halves of the object palette its enemies are drawn')
out.append('// with: bit 0 entries 0-7, bit 1 entries 8-15')
out.append('static const uint8_t kSTEnemyHalves[7] = { ' + ', '.join('%d' % (int(any(m & 1 == 0 for m in ms)) | (int(any(m & 1 for m in ms)) << 1)) for ms in monsters) + ' };')
out.append('')
out.append('#endif')
print('\n'.join(out))
