#!/usr/bin/env python3
"""
png2splash - a small image to planar splash data linked into the game.

The splash has to be on screen before any data file is read, so it
cannot live in DATA\\: it is compiled in. Screen RAM wants ST
interleaved planar, and the artwork uses three colours (background,
logo, a dimmer line of text), so two bitplanes carry it and the
other two are written as zeros at draw time.

Raw two-plane 320x200 is 16000 bytes, which is a lot of binary for a
mostly-empty image, so the rows are run-length encoded: a byte pair
(count, value) per run, counts 1..255, runs never crossing a row.
The logo compresses to a couple of hundred bytes and decodes with a
dozen instructions.

Usage:
  png2splash.py IN.png OUT.cpp [--name SYMBOL]

The image must be 320 pixels wide, at most 4 colours, and its
palette is emitted alongside the data so the game can set the
hardware registers without guessing.
"""

import argparse
import sys
from collections import Counter

try:
    from PIL import Image
except ImportError:
    sys.exit("png2splash needs Pillow: pip install pillow")

WIDTH = 320


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("output")
    # the game refers to these symbols by name, so the default has to
    # match src/game.cpp rather than the image
    ap.add_argument("--name", default="g_splash")
    args = ap.parse_args()

    im = Image.open(args.input).convert("RGB")
    w, h = im.size
    if w != WIDTH:
        sys.exit("image must be %d pixels wide, got %d" % (WIDTH, w))

    counts = Counter(im.getdata())
    if len(counts) > 4:
        sys.exit("image has %d colours, at most 4 fit two planes" % len(counts))

    # index 0 is the most common colour: the background, and the one
    # the border shows too, so it wants to be the palette's colour 0
    order = [c for c, _ in counts.most_common()]
    index = {c: i for i, c in enumerate(order)}

    rows = []
    px = im.load()
    for y in range(h):
        row = bytearray()
        for gx in range(0, WIDTH, 16):
            p0 = p1 = 0
            for bit in range(16):
                v = index[px[gx + bit, y]]
                if v & 1:
                    p0 |= 0x8000 >> bit
                if v & 2:
                    p1 |= 0x8000 >> bit
            row += bytes([p0 >> 8, p0 & 0xFF, p1 >> 8, p1 & 0xFF])
        rows.append(bytes(row))

    # RLE per row, so a decoder never has to carry a run across the
    # row boundary and can write groups as it goes
    enc = bytearray()
    for row in rows:
        i = 0
        while i < len(row):
            v = row[i]
            n = 1
            while i + n < len(row) and row[i + n] == v and n < 255:
                n += 1
            enc += bytes([n, v])
            i += n

    raw = len(rows) * len(rows[0])
    pal = []
    for c in order:
        # ST hardware is 3 bits per channel on a plain ST; the STE's
        # low bit is dropped here so the splash looks the same on both
        pal.append(tuple(v >> 5 for v in c))

    with open(args.output, "w") as f:
        f.write("/*\n")
        f.write(" * Generated by tools/png2splash.py from %s\n"
                % args.input.split("/")[-1])
        f.write(" * Do not edit: change the image and regenerate.\n")
        f.write(" *\n")
        f.write(" * %dx%d, %d colours, two bitplanes, rows run-length\n"
                % (w, h, len(order)))
        f.write(" * encoded as (count, byte) pairs: %d bytes for %d raw.\n"
                % (len(enc), raw))
        f.write(" */\n\n")
        f.write("#include \"intern.h\"\n\n")
        f.write("extern const uint16_t %s_w;\n" % args.name)
        f.write("extern const uint16_t %s_h;\n" % args.name)
        f.write("extern const uint8_t %s_pal[][3];\n" % args.name)
        f.write("extern const uint16_t %s_pal_count;\n" % args.name)
        f.write("extern const uint8_t %s_rle[];\n" % args.name)
        f.write("extern const uint32_t %s_rle_len;\n\n" % args.name)
        f.write("const uint16_t %s_w = %d;\n" % (args.name, w))
        f.write("const uint16_t %s_h = %d;\n" % (args.name, h))
        f.write("const uint16_t %s_pal_count = %d;\n"
                % (args.name, len(pal)))
        f.write("const uint8_t %s_pal[][3] = {\n" % args.name)
        for r, g, b in pal:
            f.write("\t{ %d, %d, %d },\n" % (r, g, b))
        f.write("};\n\n")
        f.write("const uint32_t %s_rle_len = %d;\n" % (args.name, len(enc)))
        f.write("const uint8_t %s_rle[] = {\n" % args.name)
        for i in range(0, len(enc), 16):
            f.write("\t" + " ".join("0x%02X," % b for b in enc[i:i + 16]) + "\n")
        f.write("};\n")

    print("%s -> %s: %dx%d, %d colours, %d bytes RLE (%d raw, %.1f%%)"
          % (args.input, args.output, w, h, len(order), len(enc), raw,
             100.0 * len(enc) / raw))
    return 0


if __name__ == "__main__":
    sys.exit(main())
